SELECT * FROM customer_behavior.customer;

USE customer_behavior ;
-- •	--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS Total_revenue
FROM customer
GROUP BY gender ;

-- Male	157890
-- Female	75191

-- •	--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and 
purchase_amount >= (SELECT AVG(purchase_amount) FROM customer );				

-- 2	64
-- 3	73
-- 4	90
-- 7	85
-- 9	97
-- 12	68
-- 13	72
-- 16	81
-- 20	90
-- 22	62                    

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, AVG(review_rating) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC 
LIMIT 5 ;

-- Gloves	3.8614285714285725
-- Sandals	3.8443750000000003
-- Boots	3.8187500000000005
-- Hat	3.8012987012987005
-- Skirt	3.784810126582278

SELECT item_purchased, ROUND(AVG(review_rating), 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC 
LIMIT 5 ;

-- Gloves	3.86
-- Sandals	3.84
-- Boots	3.82
-- Hat	3.8
-- Skirt	3.78


-- •	--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type , ROUND(AVG(purchase_amount), 2) AS Avg_purchase_amt
FROM customer
WHERE shipping_type in ('Standard' , 'Express')
GROUP BY shipping_type  ;

-- Express	60.48
-- Standard	58.46

-- •	--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status , ROUND(AVG(purchase_amount), 2) AS Avg_purchase_amt, 
ROUND(SUM(purchase_amount), 2) AS Total_revenue_amt
FROM customer
GROUP BY subscription_status ;

-- Yes	59.49	62645
-- No	59.87	170436

SELECT subscription_status , 
COUNT(Customer_id) , ROUND(AVG(purchase_amount), 2) AS Avg_purchase_amt, 
ROUND(SUM(purchase_amount), 2) AS Total_revenue_amt
FROM customer
GROUP BY subscription_status 
ORDER BY  Total_revenue_amt,  Avg_purchase_amt DESC ;

-- Yes	1053	59.49	62645
-- No	2847	59.87	170436


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied? 

SELECT item_purchased , ROUND(AVG(discount_applied = 'Yes') * 100, 2) AS Discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY Discount_rate DESC 
LIMIT 5 ;

-- Hat	50.00
-- Sneakers	49.66
-- Coat	49.07
-- Sweater	48.17
-- Pants	47.37

-- ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) as discount_rate

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH CTE_Customer_type AS (
	SELECT customer_id, previous_purchases, 
    CASE 
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
	END AS Customer_Segment
FROM Customer
)

SELECT customer_segment, COUNT(*) AS 'NumberofCustomer'
FROM CTE_Customer_type
GROUP BY customer_segment ;

-- Loyal	3116
-- Returning	701
-- New	83

-- Q8. What are the top 3 most purchased products within each category?

WITH CTE_Item_count AS 
(	SELECT category, item_purchased, 
    COUNT(Customer_id) AS Total_orders, 
    ROW_NUMBER() OVER(PARTITION BY Category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
 )
 
SELECT item_rank, category, item_purchased, total_orders
FROM CTE_item_Count
WHERE item_rank <= 3 ;

-- 1	Accessories	Jewelry	171
-- 2	Accessories	Sunglasses	161
-- 3	Accessories	Belt	161
-- 1	Clothing	Blouse	171
-- 2	Clothing	Pants	171
-- 3	Clothing	Shirt	169
-- 1	Footwear	Sandals	160
-- 2	Footwear	Shoes	150
-- 3	Footwear	Sneakers	145
-- 1	Outerwear	Jacket	163
-- 2	Outerwear	Coat	161

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT  subscription_status, COUNT(Customer_id) AS repeat_buyers
FROM Customer
WHERE previous_purchases > 5
GROUP BY subscription_status ;

-- Yes	958
-- No	2518

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, 
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC ;

-- Young Adult	62143
-- Middle-aged	59197
-- Adult	55978
-- Senior	55763
